version: '3'

services:
  devcontainer:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        DEVUSER: devuser
        DEVUID: 1000
    user: devuser
    environment:
    command: "sleep infinity"
    volumes:
      - ..:/workspaces/{{cookiecutter.project_slug}}
{%- if cookiecutter.docker_in_docker == "Yes" %}
      - //var/run/docker.sock:/var/run/docker.sock
{%- endif %}
