version: '3.4'

services:
  devcontainer:
    environment:
      - DISPLAY=host.docker.internal:0.0
    volumes:
{%- if cookiecutter.container_mount_ssh == "Yes" %}
      - ${USERPROFILE}/.ssh:/home/devuser/.ssh:ro
{%- endif %}
