version: '3.4'

services:
  devcontainer:
    environment:
      - DISPLAY=${LOCAL_DISPLAY}
      - XAUTHORITY=${LOCAL_XAUTHORITY}
    volumes:
{%- if cookiecutter.container_mount_ssh == "Yes" %}
      - ${HOME}/.ssh:/home/devuser/.ssh:ro
{%- endif %}
{%- if cookiecutter.container_mount_xorg == "Yes" %}
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - ${LOCAL_XAUTHORITY}:/home/devuser/.Xauthority:rw
{%- endif %}
{%- if cookiecutter.docker_in_docker == "Yes" %}
      - //var/run/docker.sock:/var/run/docker.sock:rw 
{%- endif %}
